### ISSUE TITLE
I am able to login to platform as a mentor/mentee after the edition close

### ISSUE THREAD

**Issue by pg20** [LearnITGirl/WebPlatform#130]

**Comment by pg20** [comment]
This happens when user login by clicking forgot password. Which automatically redirects to dashboard. Please check.

**Comment by anjali-sharma** [comment]
Looking into it.

**Comment by anjali-sharma** [comment]
@pg20 Why is the notice: "Current edition has already ended!" hardcoded in 'check_role' action of PasswordResetsController ? Where are we doing the actual check for the edition end date ? Kindly clarify.
