### ISSUE TITLE
'Other' input disappearing (Mentee evaluation form)

### ISSUE THREAD

**Issue by trajchevska** [LearnITGirl/WebPlatform#45]
In the mentee evaluation form the input for manually entering the points for a question is not showing if you select another answer in the meantime, then switch back to 'Other'. 
For example, if you select 'Other' to 'What motivated you to become a scholar', the input for entering the points is shown. Then, if you select 'Their love of coding' and then go back to 'Other' again, the input stays hidden.

**Comment by anjali-sharma** [comment]
Was able to reproduce the issue for both mentee and mentor evaluations forms. Shall push out the fix in a couple of hours.

**Comment by DMips** [comment]
@anjali-sharma :+1:
