### ISSUE TITLE
Mentor and mentee profiles are confusing

### ISSUE THREAD

**Issue by alma-castant** [LearnITGirl/WebPlatform#90]
Mentor profile doesn't show mentor email but shows mentee email on the side, and viceversa. I can create mockups for this if necessary.

**Comment by anjali-sharma** [comment]
I shall make the changes for that. Do you want the email to be displayed just below the gravatar as is the case now ?

**Comment by alma-castant** [comment]
I will prepare a mockup tomorrow ;)

**Comment by alma-castant** [comment]
https://learnit-girl.mybalsamiq.com/projects/mvpuserinterface/mentee-profile we actually have a profile already

**Comment by anjali-sharma** [comment]
@alma-castant So should profiles be changed as per this mock, i.e., eliminate the emails of both mentors and mentees from the profile ?

**Comment by learnit-girl** [comment]
@anjali-sharma I just added email. Also the mentor name should be a link to the mentor profile. And the same for the mentor profile. No other information from the other person should be shown to avoid confusion ;)

**Comment by alma-castant** [comment]
@anjali-sharma I just added email. Also the mentor name should be a link to the mentor profile. And the same for the mentor profile. No other information from the other person should be shown to avoid confusion ;)

**Comment by anjali-sharma** [comment]
:+1:  Thanks
